# Generated by Django 5.2.4 on 2025-07-25 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_first_it_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='OperationTypes',
            new_name='OperationType',
        ),
        migrations.RenameModel(
            old_name='StatusTypes',
            new_name='StatusType',
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 7, 25, 14, 59, 11, 958075, tzinfo=datetime.timezone.utc)),
        ),
    ]
