# Generated by Django 5.2.4 on 2025-07-26 16:37
# Edited by Simz0 on 2025-07-26 16:43

from django.db import migrations
from django.core.management import call_command

def load_initial_data(apps, schema_editor):
    try:
        call_command('loadinitialdata')
    except Exception as e:
        print(f"Couldn't load the start data: {str(e)}")

class Migration(migrations.Migration):

    dependencies = [
        ('test_first_it_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
