# Generated by Django 5.2.4 on 2025-07-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_first_it_app', '0002_rename_categorys_category_and_more'),
        ('test_first_it_app', '0003_auto_20250726_2337'),
    ]

    operations = [
    ]
