# Generated by Django 5.2.4 on 2025-07-26 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_first_it_app', '0004_merge_20250726_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
